// Boxing Workshop Coach Input — roster + workshop-specific phrase library.
// All phrases are training-context only — no sparring, fighting, or opponent language.
// ~30 phrases per (attribute × sentiment) slot, 5 attributes × 3 sentiments = 450 phrases.

window.VertexBoxingData = (() => {
  // ---------- 12-athlete mock workshop squad (Iron Vine Boxing — Mixed Levels) ----------
  const squad = [
    { id:'mateo',  name:'Mateo Reyes',     level:'Adv',  num:1,  initials:'MR', accent:'#9bd2ff' },
    { id:'jaylen', name:'Jaylen Brooks',   level:'Int',  num:2,  initials:'JB', accent:'#7ed7c5' },
    { id:'zaid',   name:'Zaid Karim',      level:'Beg',  num:3,  initials:'ZK', accent:'#ffbf66' },
    { id:'tariq',  name:'Tariq Owens',     level:'Int',  num:4,  initials:'TO', accent:'#c89bff' },
    { id:'leon',   name:'Leon Petros',     level:'Adv',  num:5,  initials:'LP', accent:'#ff9bb6' },
    { id:'kofi',   name:'Kofi Annang',     level:'Beg',  num:6,  initials:'KA', accent:'#8de08a' },
    { id:'devin',  name:'Devin Mahoney',   level:'Int',  num:7,  initials:'DM', accent:'#ffd56b' },
    { id:'marcus', name:'Marcus Cole',     level:'Adv',  num:8,  initials:'MC', accent:'#ff8a8a' },
    { id:'andre',  name:'Andre Volkov',    level:'Int',  num:9,  initials:'AV', accent:'#6bd5ff' },
    { id:'omar',   name:'Omar Daher',      level:'Beg',  num:10, initials:'OD', accent:'#ffafef' },
    { id:'kai',    name:'Kai Nakamura',    level:'Int',  num:11, initials:'KN', accent:'#a8e063' },
    { id:'rico',   name:'Rico Bautista',   level:'Adv',  num:12, initials:'RB', accent:'#bda6ff' },
  ];

  // ---------- Attribute palette (5 workshop blocks) ----------
  const attributes = [
    { key:'fundamentals', label:'Fundamentals', short:'FUND', topic:'Fundamentals',    glyph:'\u25C6' },
    { key:'mitts',        label:'Focus Mitts',  short:'MITT', topic:'Focus mitts',     glyph:'\u25CF' },
    { key:'noodle',       label:'Noodle',       short:'NOOD', topic:'Defense (noodle)', glyph:'\u25B2' },
    { key:'shields',      label:'Shields',      short:'SHLD', topic:'Shields/conditioning', glyph:'\u2756' },
    { key:'partner',      label:'Partner Work', short:'PART', topic:'Partner work',    glyph:'\u2605' },
  ];

  const coaches = [
    { id:'kade',   name:'Coach Kade',   initials:'CK', color:'#59b7ff' },
    { id:'reyes',  name:'Coach Reyes',  initials:'CR', color:'#ffbf66' },
    { id:'okafor', name:'Coach Okafor', initials:'CO', color:'#c89bff' },
  ];

  const sessionKinds = ['Workshop','Open Gym','Skills Block'];

  // ---------- Phrase library ----------
  // Workshop language only. Drills, technique, conditioning, partner co-operation.
  // No sparring, no opponent assessment, no "fight" framing.
  const phrases = {
    // ---- FUNDAMENTALS: jab, cross, hooks, uppercuts, stance ----
    fundamentals: {
      '+': [
        'Jab snapping back to guard fast off the line',
        'Cross rotating cleanly through the rear hip',
        'Lead hook compact, elbow at shoulder height',
        'Rear hook turning over with full hip drive',
        'Lead uppercut starting from a true bent knee',
        'Rear uppercut staying tight along the centre line',
        'Stance balanced — weight evenly through both feet',
        'Chin tucked behind the lead shoulder all session',
        'Hands returning home after every single shot',
        'Lead foot anchored before the cross fires',
        'Jab doubled cleanly without telegraphing',
        'Cross extending fully without overcommitting',
        'Hook arm angle held square — no swinging',
        'Uppercut elbow staying inside the frame',
        'Stance recovery after each combination was crisp',
        'Jab thrown straight from the chin, not loaded',
        'Rear hand glued to the cheek between shots',
        'Pivoted on the cross to find correct alignment',
        'Step-in jab maintained shoulder-width base',
        'Lead hook delivered without dropping the rear hand',
        'Uppercuts kept the back upright — no leaning in',
        'Jab-cross-hook flowed without resetting stance',
        'Front toe and back heel on the centre line',
        'Knee bend held through the whole uppercut chain',
        'Shoulder roll on jab return — disciplined',
        'Hip line and shoulder line stayed connected',
        'Rear hand return before lead hook fired',
        'Lead hook came off a real pivot, not an arm',
        'Stance width consistent from round one to four',
        'Punches finishing back to guard, not at the target',
      ],
      '=': [
        'Working on lead-hand placement during the jab',
        'Reviewing rear-hip rotation cue on the cross',
        'Drilling lead hook from the mirror this block',
        'Practicing rear uppercut from a sustained slip',
        'Resetting stance width after every combination',
        'Cueing chin-tuck before each shot',
        'Trialling shorter step on the lead-side advance',
        'Adjusting back-foot pivot timing on the cross',
        'Refining elbow path on the lead hook',
        'Sharpening uppercut path along the centre line',
        'Calibrating jab range from the wall drill',
        'Testing a slightly narrower stance for mobility',
        'Working hand-return discipline between every punch',
        'Re-teaching guard position before fatigue sets in',
        'Holding stance during 60-second isometric reset',
        'Drilling stance recovery after a one-two-three',
        'Practicing slow-tempo jab to clean up trajectory',
        'Adding hip-cue before the rear cross',
        'Iterating front-foot landing on the lead jab',
        'Walking through the four-punch combo at half speed',
        'Holding mirror-stance for posture audit',
        'Reset block: revisiting the basic two-point stance',
        'Reviewing hook plane height with the broomstick drill',
        'Shadow rounds focused on returning to guard',
        'Counting hand returns out loud during shadow',
        'Adding a chin-tuck cue between every combination',
        'Drilling jab-only round to lock in stance memory',
        'Practicing punch finish on the wall pad',
        'Working stance recovery after every footwork drill',
        'Block focused on hand-position consistency',
      ],
      '-': [
        'Jab arm drifting away from the chin on extension',
        'Cross losing rear-hip rotation when tired',
        'Lead hook swinging wide instead of pivoting',
        'Rear hook telegraphed with a shoulder dip',
        'Uppercut launched from a straight back leg',
        'Rear uppercut wandering off the centre line',
        'Stance collapsing too narrow under fatigue',
        'Chin riding high once breathing got heavy',
        'Hands not returning to guard after the cross',
        'Lead foot lifting before the cross finished',
        'Doubled jab loaded the shoulder back first',
        'Cross overextending and pulling stance forward',
        'Hooks turning into arm-only swings late in round',
        'Uppercut elbow drifting outside the frame',
        'Stance reset slow between combinations',
        'Jab loaded with a backwards shoulder cock',
        'Rear hand floating away from the cheek',
        'Cross fired without any back-foot pivot',
        'Step-in jab widened the stance unnecessarily',
        'Lead hook dropped the rear hand each rep',
        'Leaning in on uppercuts and losing posture',
        'Combinations breaking stance between shots',
        'Toe-to-heel alignment slipped through round three',
        'Knees straightened through the uppercut sequence',
        'No shoulder roll on the jab return',
        'Hip and shoulder line decoupling on hooks',
        'Hook initiated before rear hand was set',
        'Lead hook coming off an arm-only motion',
        'Stance width different every combination',
        'Finishing punches at the bag, not back to guard',
      ],
    },

    // ---- FOCUS MITTS: combinations, accuracy, form ----
    mitts: {
      '+': [
        'Hitting the centre target dead-clean on every jab',
        'Three-punch combination landing in perfect sequence',
        'Accuracy held through a full four-punch flurry',
        'Mitt sound was sharp and consistent across the round',
        'Form stayed intact even as combinations got longer',
        'Reading the mitt cue and reacting on the first frame',
        'Combinations recovered to guard between every set',
        'Five-punch chain delivered without losing tempo',
        'Quick reaction on the body-shot call',
        'Lead hook landing flush on the angled mitt',
        'Rear uppercut threading clean into the mitt slot',
        'Picked up the mitt switch without losing rhythm',
        'Stayed on the moving mitt without overreaching',
        'Combinations stayed tight and economic',
        'Snap and form both holding into the final round',
        'Mitt call answered with the right punch every time',
        'Bracketed the target — top, middle, body — cleanly',
        'Maintained head position while combinations fired',
        'Quiet feet, loud hands on the rapid-fire call',
        'Recovered guard between every two-punch set',
        'Tempo matched the mitt holder for the whole round',
        'Body-head-body combo landed in correct order',
        'Switched levels cleanly on the slip-mitt cue',
        'Stayed in the pocket for the whole combination',
        'Mitt accuracy held through the conditioning round',
        'Right elbow path on every uppercut into the mitt',
        'Combinations finished with intentional placement',
        'Lead hook found the angled mitt without telegraph',
        'Worked the full ladder without breaking form',
        'Slipped between mitt calls without losing reset',
      ],
      '=': [
        'Working through the three-punch ladder progression',
        'Drilling the jab-cross-hook on the moving mitt',
        'Practicing accuracy with the small focus pad',
        'Adding the body-shot call into every combination',
        'Building the five-punch sequence step by step',
        'Iterating on hook accuracy at the angled mitt',
        'Sharpening uppercut placement in the mitt slot',
        'Testing a slower call-and-respond mitt round',
        'Refining lead-hook elbow path on the pad',
        'Resetting guard between every combination this round',
        'Mitt round focused on form before speed',
        'Working level changes on the body-head call',
        'Practicing reaction time on the random mitt cue',
        'Building combination memory with three-shot loops',
        'Reviewing punch return on every mitt set',
        'Adding a slip between the two-punch reset',
        'Mitt block: short combinations, perfect form',
        'Drilling cross-only round to sharpen rear hand',
        'Working pivot footwork off the lead-hook mitt',
        'Holding longer combinations at half speed',
        'Reviewing accuracy through the small-mitt drill',
        'Adding sound-check focus to mitt feedback',
        'Iterating tempo over volume this mitt block',
        'Working the ladder drill from one up to five',
        'Practicing economy of motion on the heavy mitt',
        'Resetting head position between every mitt call',
        'Mitt round dedicated to consistency, not power',
        'Drilling body-shot accuracy from the closed guard',
        'Working call-and-respond at moderate tempo',
        'Adding pivot-out at the end of every combination',
      ],
      '-': [
        'Missing the centre of the mitt on the cross',
        'Combination falling apart after the third punch',
        'Reaction late on the random mitt cue',
        'Form breaking once combinations got longer',
        'Mitt sound inconsistent across the round',
        'Punches landing flat — no rotation behind them',
        'Lost guard return between mitt sets',
        'Lead hook arrived wide of the angled pad',
        'Uppercut overshooting the mitt slot',
        'Pre-loaded the cross before the mitt call landed',
        'Combinations fired with no pause for reset',
        'Mitt switch caught the athlete flat-footed',
        'Body-shot cue answered with a head shot',
        'Slipped behind the tempo of the mitt holder',
        'Overreached on a moving mitt and lost balance',
        'Form deteriorated through the conditioning round',
        'Lost level discipline between body and head',
        'Mitt accuracy dropped late in the round',
        'Bracket combination missed the middle target',
        'Hook plane slipped above shoulder height on the pad',
        'Combination tempo collapsed before round one ended',
        'Quiet feet vanished after the first 30 seconds',
        'Reset between combinations was rushed and sloppy',
        'Mitt call needed a second prompt to land',
        'Wide-swinging hooks not finding the pad',
        'Cross arrived without rear-hip rotation on the pad',
        'Uppercut elbow drifted wide of the mitt slot',
        'Combination order swapped halfway through the set',
        'Mitt holder had to slow the round to recover form',
        'Punches landing soft on the mitt — no commitment',
      ],
    },

    // ---- NOODLE: defense, blocking, slipping, footwork ----
    noodle: {
      '+': [
        'Crisp slip outside the lead-hand noodle every pass',
        'Caught the noodle with a clean high-guard block',
        'Pivoted out of range with a clean back-foot step',
        'Bent at the knees on the slip — not at the waist',
        'Returned to guard immediately after the slip',
        'Rolled under the swinging noodle without resetting',
        'Footwork stayed light through the noodle round',
        'Slip-slip-pivot sequence held its shape',
        'Read the noodle cue early on every pass',
        'Defensive head movement small and economical',
        'Front foot stepping first on the lateral move',
        'Stayed in stance through the whole defence drill',
        'Block-and-counter timing tight and disciplined',
        'Slipped outside without losing line of sight',
        'Pull-counter delivered with the back foot anchored',
        'Footwork pattern square through the boxing line',
        'Catch on the lead-hand glove was firm and quiet',
        'Slipped without overreaching the upper body',
        'Reset to centre after every defensive movement',
        'Read the noodle level and matched the slip height',
        'Half-step pivot kept the angle without breaking guard',
        'Noodle pass answered with a defensive option each time',
        'Used the L-step to exit the noodle line cleanly',
        'Defensive movement stayed inside the shoulder frame',
        'Roll under was deep but stance never widened',
        'Catch-and-pivot sequence flowed without pause',
        'Footwork stayed forward — no backwards drift',
        'Lateral pivots kept the rear hand high',
        'Read multi-direction noodle without panicking',
        'Recovered to guard within a half-second of every move',
      ],
      '=': [
        'Working on slip depth with the slow noodle pass',
        'Drilling the catch-block on the lead-hand line',
        'Practicing pivot exit after every defensive move',
        'Resetting guard at the end of each slip',
        'Iterating footwork width on the lateral drill',
        'Adding the roll-under into the noodle round',
        'Refining the L-step at the corner of the bag',
        'Reviewing slip-and-counter timing at half speed',
        'Working the front-foot-first stepping cue',
        'Building defensive sequences three moves at a time',
        'Block-and-pivot drilled in isolation this round',
        'Adding pull-counter into the noodle pattern',
        'Practicing slip without losing head over front knee',
        'Reviewing rear-hand guard during defensive moves',
        'Drilling level changes off the high noodle pass',
        'Working catch-block with quiet feet',
        'Defensive footwork round focused on returning to centre',
        'Reviewing slip plane with the broomstick drill',
        'Adding a half-step exit after every catch',
        'Practicing roll-under in the mirror this block',
        'Trialling tighter pivot radius on the L-step',
        'Working slip-slip-pivot three-count drill',
        'Reviewing knee-bend depth during slips',
        'Adding defensive call-out during the noodle round',
        'Practicing pivot-and-recover at slow tempo',
        'Working footwork on the agility ladder warmup',
        'Drilling defensive reset between slip sequences',
        'Reviewing guard position during lateral footwork',
        'Adding pivot exit into the catch-and-return drill',
        'Defence block: building one move per round',
      ],
      '-': [
        'Bending at the waist instead of the knees on slips',
        'Catch-block leaving the rear hand low',
        'Stepping with the back foot first on the lateral move',
        'Slip too deep — losing line of sight',
        'Pivot exit late and getting caught flat-footed',
        'Rolling under and standing up out of stance',
        'Defensive head movement large and exaggerated',
        'No reset to guard between slips',
        'Footwork stiff and heavy through the noodle round',
        'Reading the noodle cue half a beat too late',
        'Pull-counter losing the rear-foot anchor',
        'Drifting backwards instead of pivoting',
        'Catch leaving the hand away from the cheek',
        'Slip-slip-pivot collapsed into a single sloppy movement',
        'Stance widened during every lateral exit',
        'Head overreaching the lead knee on the slip',
        'Defensive movement breaking guard structure',
        'Roll under lifted the head above the noodle line',
        'Hand catch arrived after the noodle had passed',
        'Pivot exit dropped the rear hand',
        'L-step landed outside the boxing line',
        'Defence stalled — accepted the noodle without moving',
        'Slip plane changed each rep — inconsistent height',
        'Knee bend disappeared after two minutes',
        'Lateral footwork crossed feet under fatigue',
        'Reset to centre slow and predictable',
        'Slipped into the line of the swinging noodle',
        'Caught the noodle on the forearm instead of the glove',
        'Footwork backed into the corner instead of pivoting',
        'Lost defensive cue when sequences ran past three moves',
      ],
    },

    // ---- SHIELDS: power, stamina, conditioning ----
    shields: {
      '+': [
        'Held shield power through the full three-minute round',
        'Punching with intent on every single rep into the shield',
        'Stamina held — pace consistent from start to finish',
        'Conditioning round completed without form drop',
        'Rear-hand power firing through the hip into the shield',
        'Lead hook landing with full body rotation behind it',
        'Round-by-round output held remarkably steady',
        'Recovery between shield sets was quick and quiet',
        'Last 30 seconds of the round were the strongest',
        'Pushed pace through the shield combination ladder',
        'Maintained breathing rhythm across all four rounds',
        'Body-shot drive coming from the legs, not the arms',
        'Sustained punch volume across the conditioning block',
        'Output through the shield matched the metronome cue',
        'Power didn\u2019t fade — every shot finished',
        'Held a strong base under the shield-push drill',
        'Drove forward into the shield without losing posture',
        'Shield drill completed at full intensity from rep one',
        'Quiet recovery between sets — short, controlled breaths',
        'Body weight transferred fully into every shield shot',
        'Stayed in stance even during the burnout reps',
        'Energy distribution across the round was efficient',
        'Finished the conditioning ladder without missing a count',
        'Lifted intensity on the coach\u2019s tempo call',
        'Lead-side power equal to the rear side this block',
        'Hook into the shield travelled with full hip drive',
        'Pace held even after the second wind point',
        'Shield holder reported real impact every rep',
        'Stamina visible in the speed of guard return',
        'Pushed through the threshold mark without slowing',
      ],
      '=': [
        'Working sustained output across the three-minute shield round',
        'Drilling lead-hook power into the angled shield',
        'Building conditioning capacity with progressive shield sets',
        'Practicing breathing rhythm during the burnout block',
        'Resetting stance between every shield combination',
        'Iterating on hip drive into the body shield',
        'Reviewing pace-keeping with the metronome cue',
        'Adding a power-tempo round to the shield block',
        'Working recovery breathing in the rest between sets',
        'Drilling 30-second sprints on the shield',
        'Building base of operations under the shield push',
        'Practicing body-shot drive through the legs',
        'Reviewing intent and finish on every shield rep',
        'Resetting posture during the shield burnout',
        'Conditioning round dedicated to consistent output',
        'Working power through the shield without overcommitting',
        'Adding lead-side power reps into the rotation',
        'Building stamina with the four-round ladder',
        'Drilling combination output under the shield wall',
        'Working hip-drive cue during heavy reps',
        'Practicing economy of motion under fatigue',
        'Reviewing breath cycle across longer combinations',
        'Adding shield-push drill into the warmup',
        'Iterating tempo on the shield combination ladder',
        'Working power placement on the angled shield slot',
        'Building round-by-round consistency on the shield',
        'Drilling guard recovery during the conditioning round',
        'Reviewing stance recovery between shield sets',
        'Conditioning block: short bursts, full intent',
        'Practicing sustained pace across four rounds',
      ],
      '-': [
        'Power dropping off after 90 seconds of shield work',
        'Arm punches replacing hip drive into the shield',
        'Stamina faded through the second round',
        'Conditioning round ended early — form gone',
        'Rear hand losing rotation into the shield late',
        'Lead hook arm-only by the final 30 seconds',
        'Output uneven — first round strong, third round weak',
        'Recovery between sets too long and heavy',
        'Last minute of the round was the slowest',
        'Pace collapsed before the shield ladder finished',
        'Breathing disorganised by the second round',
        'Body shots powered from the arm, not the legs',
        'Volume drop visible from rep one of round three',
        'Output dropping below the metronome cue',
        'Punches not finishing into the shield — pulled short',
        'Lost base under the shield-push drill',
        'Drove forward but lost posture and rotation',
        'Started shield drill at half intensity',
        'Heavy, audible breathing all the way through the rest',
        'Body weight not transferring into shield shots',
        'Broke stance during the burnout reps',
        'Energy spent in the first round — nothing left for round four',
        'Skipped the last count of the conditioning ladder',
        'Intensity dropped on the coach\u2019s tempo call',
        'Lead-side power noticeably weaker than rear side',
        'Hook arrived at the shield without hip drive',
        'Pace dropped right at the second wind point',
        'Shield holder reported softening reps mid-round',
        'Guard return slowed every set as stamina dropped',
        'Stopped at the threshold mark instead of pushing through',
      ],
    },

    // ---- PARTNER WORK: composure, teamwork, coachability ----
    partner: {
      '+': [
        'Held composure when the partner drill got fast',
        'Set the partner up for clean reps every time',
        'Took the coaching cue and applied it within one rep',
        'Calm, focused energy through the whole partner round',
        'Mirrored the partner\u2019s tempo without forcing pace',
        'Said \u201creset\u201d when the drill needed it — no ego',
        'Listened all the way through the correction',
        'Adjusted on the first cue, not the third',
        'Stayed positive when the partner was learning',
        'Took feedback without defensiveness',
        'Set a controlled pace so the partner could learn',
        'Owned a missed cue and reset cleanly',
        'Coachable across all three corrections this round',
        'Encouraged the partner during the conditioning set',
        'Held back power so the partner could drill safely',
        'Asked a clear question instead of guessing',
        'Made eye contact during every coaching point',
        'Stayed engaged through the slow learning rounds',
        'Volunteered to demo the drill for the group',
        'Composure held even when the drill was new',
        'Reset the drill cleanly when the partner mistimed',
        'Adapted intensity to the partner\u2019s level',
        'Took the coach correction and shared it onward',
        'Stayed steady when the partner pushed pace',
        'Acknowledged the partner before every reset',
        'Coachability shown in three separate refinements',
        'Held the round tempo so the partner could focus',
        'Switched roles cleanly without losing focus',
        'Brought composure to a tense moment in the drill',
        'Took the cue, owned the mistake, applied it immediately',
      ],
      '=': [
        'Working composure under partner-pace pressure',
        'Drilling rep delivery to set the partner up cleanly',
        'Practicing one-cue-one-correction discipline',
        'Reviewing partner communication during reset moments',
        'Iterating role-swap cleanly between sets',
        'Adding eye-contact cue during partner corrections',
        'Building coachability with three-correction rounds',
        'Practicing reset-call when the drill drifts',
        'Working tempo mirroring with the partner',
        'Drilling controlled pace for partner safety',
        'Reviewing power calibration for partner level',
        'Adding question-asking time after each set',
        'Practicing positive reinforcement during partner reps',
        'Working composure carry between sets',
        'Drilling clean partner-handoff between drills',
        'Reviewing the coach correction loop',
        'Practicing intentional pause before each rep',
        'Building patience round on slow tempo this block',
        'Adding shared-language reset between partners',
        'Working role-clarity cue at the start of each drill',
        'Practicing applied correction within one rep',
        'Reviewing partner pace audit at round end',
        'Working composure during high-volume sets',
        'Drilling check-in language between partners',
        'Adding intentional acknowledgement after each rep',
        'Practicing measured response to coaching',
        'Working calm reset language with the partner',
        'Drilling the controlled-power partner round',
        'Adding peer-cue mirroring into the drill',
        'Reviewing composure recovery after a mistake',
      ],
      '-': [
        'Lost composure when the partner mistimed the cue',
        'Set the partner up unevenly — rushed the delivery',
        'Needed the same correction three times before applying it',
        'Energy turned tense once the drill got fast',
        'Pushed pace harder than the partner could handle',
        'Wouldn\u2019t call reset even when the drill drifted',
        'Talked over the coaching cue mid-correction',
        'Dismissed the cue and kept the old habit',
        'Visible frustration when the partner was still learning',
        'Took the feedback defensively',
        'Drove pace at the expense of the partner\u2019s focus',
        'Argued the missed cue instead of resetting',
        'Closed off after the second coach correction',
        'Ignored the partner during the conditioning set',
        'Used full power in a drill marked controlled',
        'Guessed the answer rather than asking the question',
        'Avoided eye contact during the correction',
        'Disengaged during the slow learning rounds',
        'Wouldn\u2019t volunteer for the demo',
        'Composure cracked when the drill was unfamiliar',
        'Dropped the drill rather than calling a reset',
        'Pushed intensity past the partner\u2019s level',
        'Took the coach correction and kept it to themselves',
        'Sped up when the partner asked for a slower pace',
        'Skipped the acknowledgement before the reset',
        'Coachability dropped after one correction',
        'Broke the round tempo and forced the partner to chase',
        'Switched roles abruptly without checking in',
        'Tense in a moment that needed calm',
        'Took the cue but didn\u2019t apply it the following rep',
      ],
    },
  };

  // Used for cross-slot search labels (search is strictly slot-filtered now, but
  // labels are still used when the coach types without a slot picked).
  const sentimentLabels = { '+': 'Commend', '=': 'Note', '-': 'Critique' };

  // Pre-built searchable index: flat array of { phrase, attribute, sentiment }
  const allPhrases = [];
  Object.keys(phrases).forEach(attr => {
    Object.keys(phrases[attr]).forEach(sent => {
      phrases[attr][sent].forEach(p => allPhrases.push({ phrase: p, attribute: attr, sentiment: sent }));
    });
  });

  return { squad, attributes, coaches, sessionKinds, phrases, sentimentLabels, allPhrases };
})();
