// Coach input page — squad roster + basketball-specific phrase library
// ~30 phrases per (attribute × sentiment) slot for fast search-as-you-type capture.

window.VertexCoachData = (() => {
  // ---------- 12-player mock squad (South Metro Performance, U16 girls) ----------
  const squad = [
    { id:'ava',   name:'Ava Thompson',    pos:'G/W',  num:5,  initials:'AT', accent:'#9bd2ff' },
    { id:'priya', name:'Priya Sharma',    pos:'G',    num:3,  initials:'PS', accent:'#7ed7c5' },
    { id:'mira',  name:'Mira Velasco',    pos:'G',    num:7,  initials:'MV', accent:'#ffbf66' },
    { id:'kira',  name:'Kira Bell',       pos:'W/F',  num:11, initials:'KB', accent:'#c89bff' },
    { id:'jess',  name:'Jess Tanaka',     pos:'W',    num:8,  initials:'JT', accent:'#ff9bb6' },
    { id:'tess',  name:'Tess O\u2019Connor',  pos:'F',    num:14, initials:'TO', accent:'#8de08a' },
    { id:'lana',  name:'Lana Petrov',     pos:'F',    num:23, initials:'LP', accent:'#ffd56b' },
    { id:'sam',   name:'Sam Whittaker',   pos:'F/C',  num:32, initials:'SW', accent:'#ff8a8a' },
    { id:'noor',  name:'Noor Haddad',     pos:'C',    num:44, initials:'NH', accent:'#6bd5ff' },
    { id:'evie',  name:'Evie Park',       pos:'G',    num:1,  initials:'EP', accent:'#ffafef' },
    { id:'rose',  name:'Rose Adeyemi',    pos:'W',    num:9,  initials:'RA', accent:'#a8e063' },
    { id:'mae',   name:'Mae Lindqvist',   pos:'G/W',  num:6,  initials:'ML', accent:'#bda6ff' },
  ];

  // ---------- Attribute palette ----------
  const attributes = [
    { key:'technical',    label:'Technical',    short:'TECH',  topic:'Technical skill',  glyph:'\u25C6' },
    { key:'tactical',     label:'Tactical',     short:'TAC',   topic:'Decision-making',  glyph:'\u25B2' },
    { key:'physical',     label:'Physical',     short:'PHYS',  topic:'Physical',         glyph:'\u25CF' },
    { key:'mental',       label:'Mental',       short:'MENT',  topic:'Mental',           glyph:'\u2756' },
    { key:'consistency',  label:'Consistency',  short:'CONS',  topic:'Consistency',      glyph:'\u2261' },
    { key:'leadership',   label:'Leadership',   short:'LEAD',  topic:'Leadership',       glyph:'\u2605' },
  ];

  const coaches = [
    { id:'lin',    name:'Coach Lin',    initials:'CL', color:'#59b7ff' },
    { id:'rivera', name:'Coach Rivera', initials:'CR', color:'#ffbf66' },
    { id:'vidal',  name:'Coach Vidal',  initials:'MV', color:'#c89bff' },
  ];

  const sessionKinds = ['Training','Game','Review'];

  // ---------- Phrase library ----------
  // ~30 phrases per (attribute × sentiment) slot.
  // sentiment: '+' commend, '=' neutral note, '-' critique.
  const phrases = {
    technical: {
      '+': [
        'Clean catch-and-shoot footwork on the move',
        'Inside-pivot to face up was textbook tonight',
        'Off-hand finish around the rim \u2014 both sides',
        'Floater touch over the drop big',
        'Sharp jab series before the drive',
        'Tight pocket pass out of the PnR',
        'Reverse layup choice instead of forced layup',
        'Strong two-foot stop on the catch in the paint',
        'Crisp swing-pass on the closeout',
        'Eurostep finish through the help defender',
        'Reading the front-foot of the closeout to attack',
        'Quick rip-through into the drive line',
        'Clean inside-out before the live dribble',
        'Step-back into rhythm after the side dribble',
        'Skip pass on a rope to the weakside corner',
        'Hook shot over the smaller defender in post',
        'Drop-step baseline for the easy two',
        'Wraparound dribble protected through traffic',
        'Composed snatch-back to create separation',
        'Hesitation pull-up after rejecting the screen',
        'Crossover-spin combo into the lane',
        'Stride stop on the move \u2014 perfect balance',
        'Live-dribble feed into the post over the top',
        'Behind-the-back exchange after the cross-screen',
        'Clean fake-handoff into the keeper',
        'Used the rim to shield the finish',
        'Sweep-and-go past the contesting hand',
        'Clean pin-down read into a curl',
        'Quick chest-pass into the diving roller',
        'Touch pass to the corner shooter without dribbling',
      ],
      '=': [
        'Working on hop-step into the pull-up',
        'Trying the new pin-down footwork',
        'Adding a left-hand finish package',
        'Testing the runner from the elbow',
        'Reps on inside-out dribble release',
        'Adjusted shooting base width this week',
        'New ball-screen footwork being introduced',
        'Experimenting with eurostep timing',
        'New post-entry pass technique being introduced',
        'Trial of a wider stance on the catch',
        'Working on snatch-back into the pull-up',
        'Adding a baseline drop-step to the post package',
        'Reviewing tape on her release point this week',
        'Adjusting hand placement on the live dribble',
        'Building a counter to the hard hedge',
        'Working on a one-dribble pull-up',
        'Refining footwork on the pin-down catch',
        'Practising left-hand floater technique',
        'New free-throw routine being trialled',
        'Working on dribble-handoff angles',
        'Switching to a hop step on the gather',
        'Building a step-through finish for traffic',
        'Working on the no-look pocket pass',
        'Trialling a quick-release shot this block',
        'Reviewing two-foot vs one-foot finish reads',
        'Adjusting screen-set body angle this week',
        'Testing a fadeaway turnaround in post',
        'Working on attack-the-shoulder closeout reads',
        'New entry-pass timing being introduced',
        'Reviewing tape on her pivot habits',
      ],
      '-': [
        'Travels on the gather step under pressure',
        'Drops the off-hand before the shot',
        'Releases off the front foot when rushed',
        'Picks the ball up too early on the drive',
        'No second move once the first is denied',
        'Flat shooting arc when contested',
        'Loses the dribble on the change-of-direction',
        'Footwork breaks down on pump-fake recovery',
        'Inconsistent shooting base \u2014 width keeps changing',
        'Dribbles too high under ball pressure',
        'Predictable strong-hand-only finishes',
        'Two-handed dribble on the change of pace',
        'Wide elbow on the release \u2014 leak left',
        'Fades on every contested pull-up',
        'Carries the ball on the hesi crossover',
        'Slow gather \u2014 lets the help recover',
        'Telegraphs the pass with eyes and hips',
        'Sloppy pivot footwork in the paint',
        'Off-balance on every step-back attempt',
        'Releases the floater too flat',
        'No counter to the hard hedge yet',
        'Drops the shoulder into the defender on contact',
        'Catches the ball flat-footed every time',
        'Slow on the rip-through \u2014 strip risk',
        'Dribbles into the second defender every drive',
        'Backs out of post-up without using the seal',
        'Lazy ball-screen footwork \u2014 no slip read',
        'Reaches for the handoff instead of catching solidly',
        'Releases off the wrong foot in transition',
        'No off-hand finish available right now',
      ],
    },
    tactical: {
      '+': [
        'Read the second defender before the catch',
        'Reset tempo after the trigger pass',
        'Found the skip-pass window on the swing',
        'Called the coverage early in PnR',
        'Used pace change instead of speed to get downhill',
        'Drew help and kicked to the open corner',
        'Recognised the mismatch and posted immediately',
        'Took the catch-drive-kick option over the contested pull-up',
        'Rejected the screen when the big sagged',
        'Snake-dribbled the trail defender off the screen',
        'Re-screen call when the first action stalled',
        'Drew the second tag and hit the dunker',
        'Played out of a short-clock with a quick paint touch',
        'Used the pin-in to free the corner shooter',
        'Held the dribble to let the cutter clear',
        'Spaced to the dunker spot off the live dribble',
        'Read the tag and skipped to the weakside corner',
        'Patient on the post seal before flashing back',
        'Stopped the ball and looked off the second side',
        'Drove the closeout middle, not baseline',
        'Took the right shoulder on the switch',
        'Replaced the cutter without being told',
        'Recognised the zone seam and ducked in',
        'Called a quick re-organize after the broken play',
        'Skipped to the trailer for the open three',
        'Played early to beat the rotating defence',
        'Used the screen twice before giving it up',
        'Held the pull-up to keep the offence flowing',
        'Made the simple pass when the read was clear',
        'Recognised the box-1 and ran her teammate off staggers',
      ],
      '=': [
        'Walking through the side-PnR reads on the whiteboard',
        'Reviewing late-clock decision tree',
        'Talking through advantage/disadvantage cues',
        'Testing trigger reads in 3v3 constraint',
        'Working on early-offence drag screen entries',
        'New coverage call being learned this week',
        'Adjusting spacing on the weak-side cut',
        'Looking at film of last week\u2019s broken plays',
        'New zone-offence read being installed',
        'Working through middle vs side PnR reads',
        'Reviewing live-dribble vs pass-ahead choices',
        'Adjusting reads against drop coverage',
        'New scram-switch protocol being trialled',
        'Reviewing tag-and-recover decision tree',
        'Working on counters to the hard hedge',
        'Adding a second action after the empty-side PnR',
        'Reviewing transition decision tree on numbers',
        'New BLOB option being learned',
        'Walking through hammer action timing',
        'Trial of a horns-flex read this block',
        'Working on weak-side spacing rules',
        'Reviewing late-game timeout sets',
        'New side-out concept being installed',
        'Working through pace control after a basket',
        'Adjusting reads vs ice coverage on side PnR',
        'Reviewing duck-in timing against switches',
        'New short-roll option in PnR offence',
        'Working through counters to the blitz',
        'Reviewing iso reads against switches',
        'Walking through last-shot scenarios in film',
      ],
      '-': [
        'Forced contested pull-up with a kick-out open',
        'Held the ball through the trigger window',
        'Drove into the second defender instead of resetting',
        'Missed the skip read on the swing',
        'Late to the spacing rotation on the drive',
        'Took the first read every time \u2014 predictable',
        'Wrong coverage call on the side ball-screen',
        'Drifted into the driver\u2019s lane on the corner cut',
        'Ignored the open shooter on the kick',
        'Drove into a crowd with the weak-side empty',
        'Refused the screen with the right shoulder open',
        'Held the ball too long before the trigger',
        'Took the contested two over the open three',
        'Spaced to the same spot as the cutter',
        'Drove without reading the second defender',
        'Never used the re-screen even when offered',
        'Hunted the contested shot instead of advantage',
        'Played in straight lines \u2014 no change-of-direction',
        'Took the catch and froze \u2014 no read made',
        'Skipped past the open shooter in transition',
        'Called the wrong coverage on the side action',
        'Forced the entry pass into double coverage',
        'Refused the simple pass for the hero ball',
        'Drove the closeout into the baseline trap',
        'No spacing awareness on the weakside cut',
        'Missed the mismatch and ran offence past it',
        'Hunted highlight passes over simple ones',
        'Took two dribbles into a 3v1 transition',
        'Lost track of the shot clock late in possession',
        'Stayed in iso with two cutters open',
      ],
    },
    physical: {
      '+': [
        'Sprinted the full lane on every transition',
        'Held the box-out through the whistle',
        'Won three loose balls in a row',
        'Recovered to the shooter after losing the screen',
        'Strong base on the catch \u2014 no leak',
        'Beat the rebound to the spot, not the ball',
        'Closed out high and short \u2014 no leak past',
        'Held position through contact on the post-up',
        'Won two 50-50 balls in the same possession',
        'Crashed the offensive glass every shot',
        'Played through the bump on the catch',
        'Got low through three defensive slides without standing up',
        'Beat the trailer to the corner spot',
        'Held the seal through two defenders',
        'Initiated the contact on the drive instead of avoiding it',
        'Got both hands up vertically on the contest',
        'Took the charge cleanly in transition',
        'Recovered to her shooter on the second rotation',
        'Boxed out a bigger player on multiple possessions',
        'Strong base through the screen \u2014 no slip',
        'Rim-ran every time the trigger fired',
        'Pushed the ball with pace after every defensive rebound',
        'Sustained intensity through a 90-second possession',
        'Held the lane through the second contest',
        'Played strong through the late-fourth fatigue',
        'Won the up-and-under finish with footwork strength',
        'Played through a bump without losing the dribble',
        'Sprinted back the length of the floor in transition D',
        'Sealed her defender on the cross-screen rebound',
        'Posted up off two strong dribbles into the catch',
      ],
      '=': [
        'Returning from minor knock \u2014 managed minutes',
        'Working through GPS load review this week',
        'Adjusting strength block focus',
        'Testing new mouthguard fit',
        'Recovery day scheduled tomorrow',
        'Stretching protocol updated post-session',
        'Hydration and sleep flagged green',
        'Conditioning block tomorrow before scrimmage',
        'Sleep tracking initiated for the next two weeks',
        'New plyo block introduced in pre-practice',
        'Mobility flagged as a priority this month',
        'Wearing GPS vest in scrimmage from this week',
        'New nutrition guidance shared with parents',
        'Workload monitored \u2014 minutes capped this Friday',
        'Strength benchmarks reassessed next Tuesday',
        'Recovery massage scheduled this week',
        'New jumping protocol being added pre-practice',
        'Sprint mechanics review with the S&C staff',
        'Eye-tracking screening completed',
        'New shoes being trialled \u2014 monitoring foot comfort',
        'Knee monitoring continues per the physio plan',
        'Conditioning baseline retest next Monday',
        'Wearing K-tape on the ankle preventatively',
        'Off-feet recovery prescribed for tomorrow',
        'New warmup routine being adopted by the team',
        'Cooldown protocol updated post-session',
        'Tracking lower-body soreness on the daily form',
        'New core stability work added pre-practice',
        'Workload distribution being reviewed weekly',
        'Sleep window flagged for parent conversation',
      ],
      '-': [
        'Stood and watched after the shot \u2014 no crash',
        'Lost the box-out two possessions running',
        'Heavy feet on the closeout, blew past',
        'Stopped sprinting through the third quarter',
        'Soft on contact at the rim',
        'Beaten to every loose ball in the paint',
        'Late to recover after the screen',
        'Dropped intensity on the second defensive effort',
        'No sprint back after the missed shot',
        'Walked into the closeout \u2014 no contest',
        'Avoided the contact on the seal',
        'Loafed on the third trip down',
        'Lost the rebound by ball-watching',
        'Backed out of the contest at the rim',
        'Dragged feet in transition both ways',
        'Stood upright in defensive stance',
        'Soft on the screen \u2014 every screener got loose',
        'Beaten to her spot on every cut',
        'Got tired and stopped boxing out',
        'No second jump on the offensive glass',
        'Slow rotations across the floor',
        'Avoided contact in the post-up',
        'Stopped competing in the last two minutes',
        'Refused to dive on the loose ball',
        'Last one back every transition',
        'Took the play off after the missed shot',
        'Conceded the rebound battle without trying',
        'No pace on the outlet sprint',
        'Faded out of the play after losing her matchup once',
        'Pulled off the contest after the shot fake',
      ],
    },
    mental: {
      '+': [
        'Reset cleanly after the turnover \u2014 next play mindset',
        'Composed at the line late in a tight game',
        'Took the corrective coaching cue mid-possession',
        'Stayed locked in during the long timeout',
        'Read the moment and slowed the team down',
        'Bounced back from the missed assignment within a possession',
        'Maintained focus during the officials\u2019 review',
        'Stayed engaged on the bench \u2014 clapping correct calls',
        'Refocused after the bad call without complaining',
        'Slowed her breathing before the free throw',
        'Took the timeout adjustment and applied it immediately',
        'Played fearlessly in the closing minute',
        'Showed maturity after the technical foul situation',
        'Stayed positive after going scoreless in the first half',
        'Encouraged a teammate after their turnover',
        'Maintained body language after being subbed off',
        'Owned the mistake immediately and reset',
        'Stayed in the moment despite parent noise from the sideline',
        'Used the dead ball to reset her routine',
        'Trusted the shot after missing the first two',
        'Took the coaching point without defensiveness',
        'Composed under pressing pressure late',
        'Refused to drop her head after the call',
        'Played with belief in the second-effort scoring chance',
        'Stayed switched on through the long bench shift',
        'Showed grit in the late-game scramble',
        'Owned her box-score struggles in the post-game chat',
        'Adjusted her shot routine after fatigue set in',
        'Stayed assertive after the missed open three',
        'Filtered out the crowd noise on the final possession',
      ],
      '=': [
        'Pre-game routine being refined',
        'Working through visualisation script with sports psych',
        'Talking through pressure cues in 1:1 review',
        'Trialling a new mid-game breathing reset',
        'Mindset journal entry shared with staff',
        'Reviewing high-leverage moments from last game',
        'Working on body language between possessions',
        'Pre-shot routine consistency under review',
        'New journaling prompt added post-practice',
        'Self-talk language being reviewed in 1:1',
        'Pre-game music routine being explored',
        'Working with sports psych on game-day arousal levels',
        'New visualisation cue trialled in warmup',
        'Reset protocol after errors being practised',
        'Communication style adjustment in feedback sessions',
        'Sleep and stress check-in added daily',
        'New goal-setting framework introduced this term',
        'Routine before free throws being standardised',
        'Mental load monitored alongside physical load',
        'Pre-game mindfulness segment added',
        'Working on internal vs external focus cues',
        'Reviewing high-pressure moments on film together',
        'Establishing personal performance triggers',
        'New mistake-reset cue introduced this week',
        'Self-assessment scale piloted post-game',
        'Working on cue language during huddles',
        'New breathing exercise on the bench during stoppages',
        'Talking through identity vs performance in 1:1',
        'Building tolerance to negative feedback in practice',
        'Pre-shot focus drill added to individual work',
      ],
      '-': [
        'Shoulders dropped after the missed three',
        'Argued the call instead of running back',
        'Carried the previous turnover into the next two plays',
        'Visibly frustrated after the substitution',
        'Lost focus during the late timeout',
        'Confidence dipped after a single bad rep',
        'Stopped competing once down double digits',
        'Eyes on the floor through the coach\u2019s correction',
        'Snapped at a teammate after the missed assignment',
        'Refused to make eye contact during the timeout',
        'Pouted on the bench after being subbed off',
        'Took the foul call personally and lost focus',
        'Spiralled after the first missed shot',
        'Lost composure under pressing pressure',
        'Avoided the next touch after the turnover',
        'Disengaged from the huddle in the third quarter',
        'Played tentatively after the technical situation',
        'Got rattled by an opponent\u2019s trash talk',
        'Body language dropped after the offensive rebound was taken',
        'Took the missed call as personal and went quiet',
        'Started passing up open looks after one miss',
        'Visibly anxious during the late free throws',
        'Looked to the bench every time she got the ball',
        'Carried the bad first quarter into the second',
        'Took the foul call out on the next defensive possession',
        'Crowded by the moment in the final minute',
        'Refused responsibility for the late turnover',
        'Showed frustration with officials in body language',
        'Played in fear of mistakes through the second half',
        'Stopped looking for her shot after the early miss',
      ],
    },
    consistency: {
      '+': [
        'Same shot prep every catch \u2014 no shortcuts',
        'Hit the same defensive spot four times in a row',
        'Routine before every free throw was identical',
        'Matched effort in the fourth to effort in the first',
        'Repeated the corrected footwork next possession',
        'Same call-out on every PnR coverage',
        'Stayed locked in across both halves',
        'Maintained spacing discipline every trip down',
        'Same closeout technique against every shooter',
        'Held the cut timing through every action',
        'Repeated the screen angle exactly each time',
        'Same hand placement on every box-out',
        'Identical free-throw routine ten attempts in',
        'Maintained tempo through every offensive trip',
        'Same defensive talk through both halves',
        'Built habits that held under fatigue',
        'Maintained vertical contests across the game',
        'Held shooting form through cold and hot stretches',
        'Same shot prep on the shot clock\u2019s last second',
        'Sustained communication standards on every possession',
        'Repeatable pace into every drive',
        'Held the late-clock standard across the game',
        'Same effort on every loose ball',
        'Steady through the officials\u2019 calls all night',
        'Held mechanics together late in the fourth',
        'Consistent first step on every drive',
        'Same rebound positioning trip to trip',
        'Held the same intensity in blowout minutes',
        'Identical pre-shot routine across the night',
        'Stayed task-focused through the long timeout block',
      ],
      '=': [
        'New routine being installed this block',
        'Tracking shot mechanics across the week',
        'Comparing first-half vs second-half effort metrics',
        'Reviewing repeatability of free-throw routine',
        'Testing consistency under varied fatigue',
        'Logging defensive stance percentage this session',
        'Pre-shot tempo being measured this week',
        'Drill-to-game transfer review scheduled',
        'New tracking sheet for consistency markers introduced',
        'Reviewing shot release point game over game',
        'New defensive standard set for every team block',
        'Routine consistency assessed in this week\u2019s 1:1',
        'Game-by-game effort metric being tracked',
        'Workload vs output correlation under review',
        'Pre-shot ritual standardisation in progress',
        'New cue word being layered into routines',
        'Comparing practice vs game habits on tape',
        'Quarter-by-quarter intensity log being kept',
        'Reviewing repeatability of defensive stance',
        'Standardising warmup shooting routine',
        'Standards posted in the locker room this week',
        'Daily habit tracker introduced this block',
        'Pre-game vs game-day routine alignment in review',
        'New score-margin behaviour standards introduced',
        'Reviewing how mechanics hold under fatigue',
        'Consistency benchmark test scheduled next Friday',
        'Weekly self-assessment of routine standards',
        'Standard for first-rep effort being formalised',
        'Establishing first-trip-down checklist',
        'Game-prep routine standardisation underway',
      ],
      '-': [
        'Shot mechanics changed every attempt',
        'Effort dropped sharply in the second half',
        'Routine skipped under pressure',
        'Different defensive stance every possession',
        'Made the correction once then reverted',
        'Hot first quarter, invisible in the third',
        'Spacing discipline only when ball is on her side',
        'Effort tied to scoreline, not standard',
        'Inconsistent first step from possession to possession',
        'Defensive talk loud once, then silent for the rest',
        'Free-throw routine abandoned under pressure',
        'Different shot prep every catch',
        'Effort fluctuated by quarter \u2014 unpredictable',
        'Standards dropped when fatigued',
        'Pre-shot tempo varied wildly',
        'Drill-good but game-inconsistent footwork',
        'Lost focus in repetitive drill blocks',
        'Skipped established routines when behind',
        'Box-out effort only on certain trips',
        'Same correction had to be made three times',
        'Held the standard for one quarter, then dropped',
        'Reverted to old habits after the timeout reset',
        'Picked and chose when to talk on defence',
        'Effort spiked only when scoring',
        'Closeouts inconsistent in technique',
        'Lost shape after the third turnover',
        'Body language tied to the scoreline',
        'Sustained nothing past the second quarter',
        'Free-throw mechanics changed late in game',
        'Discipline only when coach was watching',
      ],
    },
    leadership: {
      '+': [
        'Steadied teammates after the run with body language',
        'Called the coverage out loud before the screen',
        'First to the huddle after the timeout',
        'Picked up a teammate after their turnover',
        'Set the defensive talk standard early',
        'Took ownership of the rotation breakdown',
        'Modelled the routine for the younger players',
        'Voice carried across the floor in transition',
        'Rallied the group at the first stoppage after the run',
        'Praised a teammate publicly during the timeout',
        'Took accountability without being asked',
        'Held the standard for the bench during stoppages',
        'Set the warmup tone for the team',
        'Initiated the post-game group cooldown',
        'Backed up a younger teammate who was being targeted',
        'Volunteered for the toughest defensive matchup',
        'Owned the late-clock decision regardless of outcome',
        'Talked through the broken set with calm authority',
        'Communicated switch calls before the action started',
        'Set the talk standard from the first possession',
        'Took the blame for the late turnover privately to staff',
        'Lifted body language across the team in the third',
        'Owned the captain\u2019s pre-game meeting confidently',
        'Welcomed a new player into the rotation visibly',
        'Recognised a teammate\u2019s defensive stop publicly',
        'Stood up for the team during a heated moment',
        'Translated coach feedback to teammates in clear terms',
        'Anchored the back line with constant talk',
        'Owned warmup energy and pulled others up',
        'Walked over to a struggling teammate at the dead ball',
      ],
      '=': [
        'Captain rotation conversation this week',
        'Working on huddle delivery and tone',
        'Pre-game speech draft shared with staff',
        'Reviewing video of her leadership moments',
        'Mentoring a younger player this block',
        'Volunteered for the captains\u2019 standards meeting',
        'New role: lead the defensive shell call-outs',
        'Working on assertive communication in scramble',
        'New leadership shadow programme this term',
        'Captains\u2019 council meeting scheduled with staff',
        'Working on tone-of-voice in 1:1 review',
        'Trialling co-captain rotation for the next block',
        'New player-led warmup format introduced',
        'Working on her on-court coaching language',
        'New responsibility: own the defensive standards meeting',
        'Discussion of leadership style in 1:1 review',
        'Trialling new huddle protocol this game',
        'Working on conflict resolution language with peers',
        'New role: brief the team on the scouting report',
        'Captain check-in scheduled mid-season',
        'Reviewing her voice and presence on tape',
        'New mentee assigned for the second block',
        'Working with staff on assertive feedback delivery',
        'Setting weekly leadership goals with sports psych',
        'New role: leading the daily warmup routine',
        'Working on giving direct feedback to teammates',
        'Captains\u2019 standards review this Friday',
        'New responsibility: run the cooldown stretch',
        'Trial of player-led timeout summary',
        'Working on her question-asking with officials',
      ],
      '-': [
        'Quieter in the huddle after early mistakes',
        'No call-outs on the back-line through the third',
        'Body language dropped \u2014 team followed',
        'Avoided eye contact during the coaching point',
        'Let the turnover spiral without resetting the group',
        'Sat at the end of the bench during the timeout',
        'Pointed at a teammate instead of owning the breakdown',
        'Voice disappeared once the deficit grew',
        'Stopped talking on defence after the second quarter',
        'Walked away from a struggling teammate mid-possession',
        'Refused to make eye contact in the huddle',
        'Blamed officials publicly during the timeout',
        'Took the credit but not the responsibility post-game',
        'Disengaged from the captains\u2019 meeting',
        'Stayed silent during the strategy discussion',
        'Did not address the post-game team huddle',
        'Skipped the team cooldown without explanation',
        'Mocked a teammate\u2019s missed shot inadvertently',
        'Avoided the difficult conversation with a teammate',
        'Took body language cues from the scoreboard',
        'Left a younger teammate to face the press without help',
        'Let the older voices override her on the floor',
        'Visible eye-roll at a teammate\u2019s mistake',
        'Did not own the late-game breakdown publicly',
        'Skipped the pre-game speech opportunity',
        'Avoided the captains\u2019 meeting two weeks running',
        'Faded out of leadership when fatigued',
        'Did not back up a teammate in a heated moment',
        'Allowed bench standards to drop without intervening',
        'Stayed inside her own performance, ignored the group',
      ],
    },
  };

  // Used for cross-slot search labels
  const sentimentLabels = { '+': 'Commend', '=': 'Note', '-': 'Critique' };

  // Pre-built searchable index: flat array of { phrase, attribute, sentiment }
  const allPhrases = [];
  Object.keys(phrases).forEach(attr => {
    Object.keys(phrases[attr]).forEach(sent => {
      phrases[attr][sent].forEach(p => allPhrases.push({ phrase: p, attribute: attr, sentiment: sent }));
    });
  });

  return { squad, attributes, coaches, sessionKinds, phrases, sentimentLabels, allPhrases };
})();
